# {{scheme-name}} — session setup.
#
# GENERATED by `just theme` from schemes/{{scheme-slug}}.yaml.
# Edit templates/hooks/on-activate.sh instead; see AGENTS.md.
#
# Runs once, when the session is created. Declared as a lifecycle hook in
# cozy.toml; minimal runs hook scripts under POSIX sh unless a shebang says
# otherwise, so this file deliberately has no shebang and no bashisms.
#
# EVERY PATH THROUGH THIS FILE MUST EXIT 0. A failing on_activate fails the
# activation and the session never becomes attachable — nothing here is worth
# costing you the session, so each step is guarded and the file ends in a bare
# `exit 0`.

set -u

slug='{{scheme-slug}}'

# --- delta -----------------------------------------------------------------
# delta has no config file of its own; it reads [delta] out of git config, so
# point git at the include the loadout ships.
#
# --add after checking the existing values, never a plain set: `git config
# --global include.path X` REPLACES what is already there, which would silently
# drop an include of your own. Matching on the basename means an entry added as
# an absolute path is recognised rather than duplicated.
#
# The `~` stays literal — git expands it, the shell must not. This step does not
# depend on the patch having landed: git ignores an include whose file is
# missing, and picks it up as soon as it appears.
#
# `case` rather than grep: grep is not in the loadout's package list (ripgrep
# is, and coreutils does not ship grep), so it may not exist in the session. If
# it were missing, `! ... | grep -q` would evaluate true and append a duplicate
# include on every activation. Pattern matching is a shell builtin and can't
# fail that way.
if command -v git >/dev/null 2>&1; then
    existing=$(git config --global --get-all include.path 2>/dev/null || true)
    case "$existing" in
        *cozy-delta.gitconfig*) ;; # already pointed at ours, in any spelling
        *) git config --global --add include.path '~/.config/git/cozy-delta.gitconfig' || true ;;
    esac
fi

# --- bat -------------------------------------------------------------------
# bat compiles themes into a cache and cannot see a .tmTheme until that cache is
# rebuilt. delta reads the same cache for in-diff highlighting, so skipping this
# leaves both off-scheme and delta falls back to Monokai.
#
# Whether `patches` are applied before or after on_activate is not documented,
# so this only fires when the theme file is actually on disk. hooks/on-attach.sh
# covers the other ordering.
if command -v bat >/dev/null 2>&1 && [ -f "$HOME/.config/bat/themes/$slug.tmTheme" ]; then
    bat cache --build >/dev/null 2>&1 || true
fi

exit 0
