# Portable fish config (loadout edition).

status is-interactive; or exit

# --- Aliases ---
if command -q eza
    alias eza 'eza --icons auto --git'
    alias ls eza
    alias la 'eza -a'
    alias ll 'eza -l'
    alias lla 'eza -la'
    alias lt 'eza --tree'
end

if command -q fd
    alias fd 'fd --hidden'
end

# --- Colours: {{scheme-name}} ---
# GENERATED by `just theme` — see README.md.
#
# Hex is set explicitly rather than via ANSI names (green, brblack, …) so the
# palette is identical regardless of what the host terminal's 16-colour table
# happens to hold.
set -g __cozy_b00 {{base00-hex}} # default background
set -g __cozy_b01 {{base01-hex}} # lighter surface
set -g __cozy_b02 {{base02-hex}} # selection
set -g __cozy_b03 {{base03-hex}} # comments, dim text
set -g __cozy_b04 {{base04-hex}} # secondary text
set -g __cozy_b05 {{base05-hex}} # default foreground
set -g __cozy_b06 {{base06-hex}} # light foreground (rare)
set -g __cozy_b07 {{base07-hex}} # lightest (rare)
set -g __cozy_b08 {{base08-hex}} # red
set -g __cozy_b09 {{base09-hex}} # orange
set -g __cozy_b0a {{base0A-hex}} # yellow
set -g __cozy_b0b {{base0B-hex}} # green
set -g __cozy_b0c {{base0C-hex}} # cyan
set -g __cozy_b0d {{base0D-hex}} # blue
set -g __cozy_b0e {{base0E-hex}} # purple
set -g __cozy_b0f {{base0F-hex}} # brown

set -g fish_color_normal $__cozy_b05
set -g fish_color_command $__cozy_b0d
set -g fish_color_keyword $__cozy_b0e
set -g fish_color_quote $__cozy_b0b
set -g fish_color_redirection $__cozy_b0c
set -g fish_color_end $__cozy_b0e
set -g fish_color_error $__cozy_b08
set -g fish_color_param $__cozy_b05
set -g fish_color_option $__cozy_b0c
set -g fish_color_comment $__cozy_b03
set -g fish_color_operator $__cozy_b0c
set -g fish_color_escape $__cozy_b0f
set -g fish_color_autosuggestion $__cozy_b03
set -g fish_color_cwd $__cozy_b0b
set -g fish_color_cwd_root $__cozy_b08
set -g fish_color_user $__cozy_b0b
set -g fish_color_host $__cozy_b0d
set -g fish_color_host_remote $__cozy_b0e
set -g fish_color_status $__cozy_b08
set -g fish_color_cancel -r
set -g fish_color_history_current --bold
set -g fish_color_valid_path --underline
set -g fish_color_match --background=$__cozy_b02
set -g fish_color_search_match --background=$__cozy_b02
set -g fish_color_selection $__cozy_b05 --bold --background=$__cozy_b02
set -g fish_pager_color_completion $__cozy_b05
set -g fish_pager_color_description $__cozy_b04
set -g fish_pager_color_prefix $__cozy_b0c --bold
set -g fish_pager_color_progress $__cozy_b04 --background=$__cozy_b01
set -g fish_pager_color_selected_background --background=$__cozy_b02

# --- Terminal surface: OSC 10/11/12 and the base16 ANSI table (OSC 4) ---
# The settings above only cover fish's own output. These hand the same palette
# to the *terminal*, which is the only way to colour the surface behind things
# that don't paint their own background — the prompt, bat, delta, bottom's
# widget text — and it makes the 16-colour table itself on-scheme, so a program
# that still speaks in ANSI names lands in the palette rather than in whatever
# the emulator shipped with.
#
# The ANSI mapping is the standard base16 one tabulated in README.md. Note what
# it costs: slots 9–14 go to the greyscale ramp and the leftover accents, so a
# program asking for "bright green" gets base01, a dark surface grey. That is
# the usual base16 trade for having all 16 slots on-scheme.
#
# $__COZY_TERM_THEMED is exported, so nested shells and zellij panes inherit
# it and skip both the apply and the reset. Only the outermost fish owns the
# terminal's colours, and it puts them back when it exits — otherwise an inner
# shell exiting would strip the palette out from under the shell still running,
# and sshing into a box with this loadout would leave your local terminal
# recoloured after you logged out.
# Every sequence is terminated with ST written as `\e\x5c`, and only one
# sequence is emitted per printf. Both are deliberate: fish's single quotes are
# not literal — they collapse `\\` to `\` before printf ever sees the string —
# so the natural-looking '\e]10;…\e\\\e]11;…' silently loses an escape and
# prints a stray "e" instead of the second ESC. `\x5c` has no such ambiguity.
if test "$TERM" != dumb; and not set -q __COZY_TERM_THEMED
    set -gx __COZY_TERM_THEMED 1

    printf '\e]10;#%s\e\x5c' $__cozy_b05 # foreground
    printf '\e]11;#%s\e\x5c' $__cozy_b00 # background
    printf '\e]12;#%s\e\x5c' $__cozy_b05 # cursor

    # ANSI 0–15. One sequence per slot rather than a single multi-pair OSC 4:
    # both are legal, but the per-slot form is what every terminal that
    # implements OSC 4 at all accepts.
    set -l __cozy_ansi \
        $__cozy_b00 $__cozy_b08 $__cozy_b0b $__cozy_b0a \
        $__cozy_b0d $__cozy_b0e $__cozy_b0c $__cozy_b05 \
        $__cozy_b03 $__cozy_b09 $__cozy_b01 $__cozy_b02 \
        $__cozy_b04 $__cozy_b06 $__cozy_b0f $__cozy_b07
    for __cozy_i in (seq 16)
        printf '\e]4;%d;#%s\e\x5c' (math $__cozy_i - 1) $__cozy_ansi[$__cozy_i]
    end
    set -e __cozy_i

    function __cozy_restore_terminal --on-event fish_exit
        # OSC 110/111/112 reset foreground/background/cursor; OSC 104 with no
        # parameter resets the whole colour table.
        printf '\e]110\e\x5c'
        printf '\e]111\e\x5c'
        printf '\e]112\e\x5c'
        printf '\e]104\e\x5c'
    end
end

# --- Welcome banner ---
# The Minimal mark, in base0D — the same accent helix gives headings, zellij
# gives the active ribbon and starship gives the working directory.
#
# fish's stock fish_greeting function prints $fish_greeting verbatim, newlines
# and escape sequences included, so setting the variable is all this needs. It
# is built here rather than down in Misc because it needs the palette variables
# still in scope — they are erased immediately below. Continuation lines start
# hard against the left margin on purpose: any indent would land inside the art.
set -g fish_greeting (set_color $__cozy_b0d)"   ████  ████▄
▄▄▄ ▀███▄ ▀███▄
▀███  ▀███  ▀███"(set_color normal)

set -e __cozy_b00 __cozy_b01 __cozy_b02 __cozy_b03 __cozy_b04 __cozy_b05 __cozy_b06 __cozy_b07 \
    __cozy_b08 __cozy_b09 __cozy_b0a __cozy_b0b __cozy_b0c __cozy_b0d __cozy_b0e __cozy_b0f

# --- zellij auto-start (kept before starship, as in the original) ---
if command -q zellij; and test "$TERM" != dumb
    eval (zellij setup --generate-auto-start fish | string collect)
end

# --- starship prompt ---
if command -q starship; and test "$TERM" != dumb
    starship init fish | source
end

if command -q zoxide
    zoxide init --cmd cd fish | source
end

# --- broot `br` launcher: regenerated from the binary, no shipped script ---
if command -q broot
    broot --print-shell-function fish | source
end

# --- fzf (fuzzy finder) ---
if command -q fzf
    fzf --fish | source

    # zellij claims Ctrl-T (tab mode), so it never reaches fzf inside a
    # session. Move the file picker to Alt-T — zellij ignores it, and it
    # still works in a bare terminal. Ctrl-R (history) and Alt-C (cd) don't
    # collide with zellij's defaults, so they're left as-is.
    bind \et fzf-file-widget

    set -gx FZF_DEFAULT_OPTS '--height 40% --layout=reverse --border'
    if command -q fd
        set -gx FZF_DEFAULT_COMMAND 'fd --hidden --strip-cwd-prefix --exclude .git'
        set -gx FZF_CTRL_T_COMMAND "$FZF_DEFAULT_COMMAND"
        set -gx FZF_ALT_C_COMMAND 'fd --type d --hidden --strip-cwd-prefix --exclude .git'
    end
    command -q bat; and set -gx FZF_CTRL_T_OPTS "--preview 'bat --color=always --style=numbers {}'"
    command -q eza; and set -gx FZF_ALT_C_OPTS "--preview 'eza --tree --color=always --icons {}'"
end

# --- Misc ---
# $fish_greeting is the banner, set up in the colours section above. Clear it
# with `set fish_greeting` here to go back to a silent shell.

function __force_repaint --on-event fish_postexec
    commandline -f repaint
end
