# Portable fish config (loadout edition).

status is-interactive; or exit

# --- PATH ---
# A minimal session starts with PATH=/usr/bin:/bin:/usr/sbin:/sbin:/home/.local/bin
# (sandbox2's `command_env`), so `pip --user` and anything else honouring
# ~/.local/bin is already reachable and the per-language directories are not.
# Everything below is a language toolchain's default install prefix, which is
# where `cargo install`, `go install` and a `--prefix`-configured npm put the
# binaries you asked them to put somewhere.
#
# `fish_add_path` skips directories that don't exist, so listing a toolchain
# nobody installed costs nothing and adds nothing — no guards needed. It also
# skips entries already present, which is why ~/.local/bin can be named here
# without ending up in PATH twice.
#
# `--global`, not the default universal: a universal variable is written to
# ~/.config/fish/fish_variables and persists, so the default would have every
# session accumulating entries into a file the loadout doesn't manage. Global
# is rebuilt from this line on each shell and leaves nothing behind.
#
# Above the aliases on purpose. Every `command -q` below is a PATH lookup, so a
# tool installed into one of these directories is invisible to all of them if
# this runs afterwards.
fish_add_path --global $HOME/.cargo/bin $HOME/go/bin $HOME/.local/bin

# --- Aliases ---
if command -q eza
    alias eza 'eza --icons auto --git'
    alias ls eza
    alias la 'eza -a'
    alias ll 'eza -l'
    alias lla 'eza -la'
    alias lt 'eza --tree'
end

if command -q fd
    alias fd 'fd --hidden'
end

# duf picks its theme from COLORFGBG, which nothing in a session sets, so it
# guesses dark and gets a light scheme wrong. The scheme knows the answer at
# render time, so a dark/light section pair decides it here.
#
# (Those markers cannot be named literally in a comment — not even in this one,
# which is why they are described rather than shown. Jinja parses the whole
# template, comments included, so an unbalanced block tag in prose is a syntax
# error and a doubled-brace placeholder in prose is an undefined-name error
# under the strict setting. Jinja does have a verbatim block that would exempt a
# region, but nothing here needs one, so none is used.)
if command -q duf
    alias duf 'duf --theme {% if dark %}dark{% endif %}{% if light %}light{% endif %}'
end

# --- Colours: {{scheme_name}} ---
# GENERATED by `just theme` — see AGENTS.md.
#
# Hex is set explicitly rather than via ANSI names (green, brblack, …) so the
# palette is identical regardless of what the host terminal's 16-colour table
# happens to hold.
set -g __cozy_b00 {{base00_hex}} # default background
set -g __cozy_b01 {{base01_hex}} # lighter surface
set -g __cozy_b02 {{base02_hex}} # selection
set -g __cozy_b03 {{base03_hex}} # comments, dim text
set -g __cozy_b04 {{base04_hex}} # secondary text
set -g __cozy_b05 {{base05_hex}} # default foreground
set -g __cozy_b06 {{base06_hex}} # light foreground (rare)
set -g __cozy_b07 {{base07_hex}} # lightest (rare)
set -g __cozy_b08 {{base08_hex}} # red
set -g __cozy_b09 {{base09_hex}} # orange
set -g __cozy_b0a {{base0A_hex}} # yellow
set -g __cozy_b0b {{base0B_hex}} # green
set -g __cozy_b0c {{base0C_hex}} # cyan
set -g __cozy_b0d {{base0D_hex}} # blue
set -g __cozy_b0e {{base0E_hex}} # purple
set -g __cozy_b0f {{base0F_hex}} # brown

set -g fish_color_normal $__cozy_b05
set -g fish_color_command $__cozy_b0d
set -g fish_color_keyword $__cozy_b0e
set -g fish_color_quote $__cozy_b0b
set -g fish_color_redirection $__cozy_b0c
set -g fish_color_end $__cozy_b0e
set -g fish_color_error $__cozy_b08
set -g fish_color_param $__cozy_b05
set -g fish_color_option $__cozy_b0c
set -g fish_color_comment $__cozy_b03
set -g fish_color_operator $__cozy_b0c
set -g fish_color_escape $__cozy_b0f
set -g fish_color_autosuggestion $__cozy_b03
set -g fish_color_cwd $__cozy_b0b
set -g fish_color_cwd_root $__cozy_b08
set -g fish_color_user $__cozy_b0b
set -g fish_color_host $__cozy_b0d
set -g fish_color_host_remote $__cozy_b0e
set -g fish_color_status $__cozy_b08
set -g fish_color_cancel -r
set -g fish_color_history_current --bold
set -g fish_color_valid_path --underline
set -g fish_color_match --background=$__cozy_b02
set -g fish_color_search_match --background=$__cozy_b02
set -g fish_color_selection $__cozy_b05 --bold --background=$__cozy_b02
set -g fish_pager_color_completion $__cozy_b05
set -g fish_pager_color_description $__cozy_b04
set -g fish_pager_color_prefix $__cozy_b0c --bold
set -g fish_pager_color_progress $__cozy_b04 --background=$__cozy_b01
set -g fish_pager_color_selected_background --background=$__cozy_b02

# --- Terminal surface: OSC 10/11/12 and the base16 ANSI table (OSC 4) ---
# The settings above only cover fish's own output. These hand the same palette
# to the *terminal*, which is the only way to colour the surface behind things
# that don't paint their own background — the prompt, bat, delta, bottom's
# widget text — and it makes the 16-colour table itself on-scheme, so a program
# that still speaks in ANSI names lands in the palette rather than in whatever
# the emulator shipped with.
#
# The ANSI mapping is the standard base16 one tabulated in AGENTS.md. Note what
# it costs: slots 9–14 go to the greyscale ramp and the leftover accents, so a
# program asking for "bright green" gets base01, a dark surface grey. That is
# the usual base16 trade for having all 16 slots on-scheme.
#
# Every sequence is terminated with ST written as `\e\x5c`, and only one
# sequence is emitted per printf. Both are deliberate: fish's single quotes are
# not literal — they collapse `\\` to `\` before printf ever sees the string —
# so the natural-looking '\e]10;…\e\\\e]11;…' silently loses an escape and
# prints a stray "e" instead of the second ESC. `\x5c` has no such ambiguity.
#
# The palette is baked into the function body at render time rather than read
# from the $__cozy_b* variables: a fish function resolves its body when it runs,
# and those variables are erased at the end of this file.
function __cozy_apply_terminal --description 'Hand the scheme to the terminal over OSC'
    printf '\e]10;#%s\e\x5c' {{base05_hex}} # foreground
    printf '\e]11;#%s\e\x5c' {{base00_hex}} # background
    printf '\e]12;#%s\e\x5c' {{base05_hex}} # cursor

    # ANSI 0–15. One sequence per slot rather than a single multi-pair OSC 4:
    # both are legal, but the per-slot form is what every terminal that
    # implements OSC 4 at all accepts.
    set -l ansi \
        {{base00_hex}} {{base08_hex}} {{base0B_hex}} {{base0A_hex}} \
        {{base0D_hex}} {{base0E_hex}} {{base0C_hex}} {{base05_hex}} \
        {{base03_hex}} {{base09_hex}} {{base01_hex}} {{base02_hex}} \
        {{base04_hex}} {{base06_hex}} {{base0F_hex}} {{base07_hex}}
    for i in (seq 16)
        printf '\e]4;%d;#%s\e\x5c' (math $i - 1) $ansi[$i]
    end
end

# The mtime of the file minimal rewrites on every attach. Its *contents* (TERM
# today) are minimal's business; only the fact that it was just rewritten is
# ours. `path mtime` is a builtin, so this costs no process per prompt, and the
# path is hard-coded for the same reason minimal hard-codes it in its own hook:
# a variable of that name could otherwise redirect the check.
function __cozy_attach_stamp
    path mtime -- $HOME/.local/state/minimal/attach-env.fish 2>/dev/null
end

# $__COZY_TERM_THEMED is exported, so nested shells and zellij panes inherit it
# and skip the initial apply and the reset. Only the outermost fish *owns* the
# terminal's colours, and it puts them back when it exits — otherwise an inner
# shell exiting would strip the palette out from under the shell still running,
# and sshing into a box with this loadout would leave your local terminal
# recoloured after you logged out.
if test "$TERM" != dumb; and not set -q __COZY_TERM_THEMED
    set -gx __COZY_TERM_THEMED 1
    __cozy_apply_terminal

    function __cozy_restore_terminal --on-event fish_exit
        # OSC 110/111/112 reset foreground/background/cursor; OSC 104 with no
        # parameter resets the whole colour table.
        printf '\e]110\e\x5c'
        printf '\e]111\e\x5c'
        printf '\e]112\e\x5c'
        printf '\e]104\e\x5c'
    end
end

# Re-apply when a *new terminal* attaches, not just once per shell.
#
# A session shell is spawned once and outlives the terminals that attach to it,
# so the palette is a per-attach fact in exactly the way minimal treats TERM as
# one: it republishes ~/.local/state/minimal/attach-env.fish on every attach and
# ships a vendor_conf.d hook that sources it. On re-attach the daemon replays a
# vt100 screen dump of the session, which carries cells and attributes but not
# the terminal's OSC palette — so without this, a second attach (and especially
# one from a different terminal) lands on an unthemed surface with nothing left
# to fix it.
#
# On fish_prompt *and* fish_preexec, mirroring minimal's own pair, for the
# reason it gives: the prompt on screen after a re-attach was drawn before the
# detach and has already fired its prompt event, so without the preexec half the
# first command you type would still run under the old terminal's palette.
#
# Unguarded by $__COZY_TERM_THEMED, unlike the apply above. The outermost fish
# hands over to zellij and then sits blocked for the rest of the session, so it
# is never the one that notices; the fish inside each pane has to. Re-emitting
# the same palette is idempotent, so panes racing each other after an attach
# costs nothing. (Whether zellij forwards a pane's OSC set to the host terminal
# is still unconfirmed — see README's Known gaps.)
if test "$TERM" != dumb
    set -g __cozy_attach_seen (__cozy_attach_stamp)

    function __cozy_reapply_terminal --on-event fish_prompt --on-event fish_preexec
        set -l now (__cozy_attach_stamp)
        # Equal covers the no-minimal-session case too: both sides stay empty,
        # so outside a session this never fires and the startup apply stands.
        test "$now" = "$__cozy_attach_seen"; and return
        set -g __cozy_attach_seen $now
        __cozy_apply_terminal
    end
end

# --- Welcome banner ---
# The Minimal mark in base07, the extreme end of the greyscale ramp. Note that
# this is "white" only in a dark scheme: base16 reverses the ramp for light
# schemes, so base07 there is the darkest slot. Either way it is the maximum
# contrast the scheme has against base00, which is what the mark wants. The
# detach hint highlights the key in base0D, the accent helix gives headings and
# zellij gives the active ribbon.
#
# fish's stock fish_greeting function prints $fish_greeting verbatim, newlines
# and escape sequences included, so setting the variable is all this needs. It
# is built here rather than down in Misc because it needs the palette variables
# still in scope — they are erased immediately below.
#
# Two layout notes, both about literal whitespace: continuation lines start hard
# against the left margin because any indent would land inside the art, and the
# blank line separating the mark from the welcome text is a real newline inside
# the quotes because fish does not expand \n in a double-quoted string.
set -g fish_greeting (set_color $__cozy_b07)"   ████  ████▄
▄▄▄ ▀███▄ ▀███▄
▀███  ▀███  ▀███

"(set_color $__cozy_b05)"Welcome to minimal! "(set_color $__cozy_b0d)"ctrl-w"(set_color $__cozy_b05)" to detach"(set_color normal)

set -e __cozy_b00 __cozy_b01 __cozy_b02 __cozy_b03 __cozy_b04 __cozy_b05 __cozy_b06 __cozy_b07 \
    __cozy_b08 __cozy_b09 __cozy_b0a __cozy_b0b __cozy_b0c __cozy_b0d __cozy_b0e __cozy_b0f

# --- zellij auto-start (kept before starship, as in the original) ---
if command -q zellij; and test "$TERM" != dumb
    eval (zellij setup --generate-auto-start fish | string collect)
end

# --- starship prompt ---
if command -q starship; and test "$TERM" != dumb
    starship init fish | source
end

if command -q zoxide
    zoxide init --cmd cd fish | source
end

# --- broot `br` launcher: regenerated from the binary, no shipped script ---
if command -q broot
    broot --print-shell-function fish | source
end

# --- Key bindings ---
# Modal editing, to match the editor the loadout ships. fish has no helix
# preset — `fish_default_key_bindings`, `fish_vi_key_bindings` and
# `fish_hybrid_key_bindings` are the entire set — so hybrid is as close as it
# gets: vi's modes (normal/insert/visual, and helix's normal/insert/select is
# the same shape) with the emacs bindings kept in every one of them. Straight
# vi mode drops ctrl-a, ctrl-e, ctrl-k and alt-. in insert mode, which are the
# keys the rest of this file's tooling assumes you still have.
#
# starship was already configured for this and had nothing to report it: its
# [character] block sets vimcmd_symbol, vimcmd_replace_symbol and
# vimcmd_visual_symbol, none of which can render while the shell is in emacs
# mode. Turning this on is what makes those four lines do something.
#
# Placed above the fzf and atuin blocks. Order turns out *not* to be
# load-bearing — switching preset runs `bind --erase --all --preset`, which
# clears preset bindings only, so bindings those tools add with a plain `bind`
# survive a later switch (verified both ways round on fish 4.8). It is written
# this way anyway, because the tools bind against whatever mode set is in
# effect and reading it in that order is how you would expect it to work.
#
# The one genuine interaction is atuin's, and it resolves itself: atuin binds
# `?` in the default mode, which under a modal preset is *normal* mode rather
# than the mode you type in. Its handler checks `$fish_key_bindings` by name
# and suppresses the literal insert for exactly `fish_vi_key_bindings` and
# `fish_hybrid_key_bindings`, so normal-mode `?` isn't shadowed by a stray
# question mark. That check is on the value of this variable, so setting it to
# either of those two names is what keeps atuin correct — a third preset, or a
# wrapper function with another name, would silently lose that.
if test "$TERM" != dumb
    set -g fish_key_bindings fish_hybrid_key_bindings

    # Cursor shape per mode — the other half of the mode indicator, and the
    # half you see without looking away from what you are typing.
    set -g fish_cursor_default block
    set -g fish_cursor_insert line
    set -g fish_cursor_visual block
    set -g fish_cursor_replace underscore
    set -g fish_cursor_replace_one underscore

    # fish only emits the cursor-shape escape for terminals it recognises, and
    # inside a session it is inspecting zellij rather than the terminal zellij
    # is drawing to. Forcing it is the difference between a mode indicator and
    # a prompt glyph you have to go looking for. Terminals that don't implement
    # the sequence ignore it, the same way they ignore the OSC palette above.
    set -g fish_vi_force_cursor 1
end

# --- fzf (fuzzy finder) ---
if command -q fzf
    fzf --fish | source

    # zellij claims Ctrl-T (tab mode), so it never reaches fzf inside a
    # session. Move the file picker to Alt-T — zellij ignores it, and it
    # still works in a bare terminal. Ctrl-R (history) and Alt-C (cd) don't
    # collide with zellij's defaults, so they're left as-is.
    #
    # Bound in insert mode as well as the default one. `bind` with no `-M`
    # touches only the default mode, which is all a vi-mode user is *not* in
    # while typing — so without the second line the rebinding silently does
    # nothing for them and Alt-T inserts a literal character instead.
    #
    # Not hypothetical: the Key bindings section above puts every shell into a
    # modal preset, so the default mode here is normal mode and the second line
    # is the one that carries Alt-T for the mode you actually type in.
    bind \et fzf-file-widget
    bind -M insert \et fzf-file-widget

    set -gx FZF_DEFAULT_OPTS '--height 40% --layout=reverse --border'
    if command -q fd
        set -gx FZF_DEFAULT_COMMAND 'fd --hidden --strip-cwd-prefix --exclude .git'
        set -gx FZF_CTRL_T_COMMAND "$FZF_DEFAULT_COMMAND"
        set -gx FZF_ALT_C_COMMAND 'fd --type d --hidden --strip-cwd-prefix --exclude .git'
    end
    command -q bat; and set -gx FZF_CTRL_T_OPTS "--preview 'bat --color=always --style=numbers {}'"
    command -q eza; and set -gx FZF_ALT_C_OPTS "--preview 'eza --tree --color=always --icons {}'"
end

# --- atuin (shell history) ---
# AFTER fzf, and that ordering is load-bearing. `fzf --fish` binds ctrl-r to its
# own history widget and `atuin init fish` binds ctrl-r (and the up arrow) to
# atuin's; whichever runs last owns the key. atuin is the one with the database
# behind it, so it goes second. Moving this block above the fzf one silently
# gives you fzf's flat history search instead — both are bound, both look
# plausible, and nothing reports the collision.
#
# The colours come from ~/.config/atuin/themes/{{scheme_slug}}.toml, patched in
# beside atuin's config.toml, which names that slug. Neither is generated here.
if command -q atuin
    atuin init fish | source
end

# --- Tool colours that travel in the environment ---
# These four have no config file to patch: they are read from the environment,
# so they are set here rather than in cozy.toml's [vars]. That is deliberate —
# vars compose across every contributor and a differing value is a hard
# activation failure, so anything that can live in the shell config does.
#
# The palette is written out at render time rather than read from the
# $__cozy_b* variables: those are erased further up this file, before any of
# this runs.

# jq takes eight colon-separated SGR sequences, in jv_kind order:
# null:false:true:numbers:strings:arrays:objects:objectkeys. Only [0-9;] is
# accepted per field, which leaves truecolour (`38;2;R;G;B`) available and
# rules out anything else. A malformed value is loud — jq prints
# "Failed to set $JQ_COLORS" on stderr rather than quietly using its defaults.
if command -q jq
    set -gx JQ_COLORS (string join ':' \
        "0;38;2;{{base03_rgb_r}};{{base03_rgb_g}};{{base03_rgb_b}}" \
        "0;38;2;{{base08_rgb_r}};{{base08_rgb_g}};{{base08_rgb_b}}" \
        "0;38;2;{{base0B_rgb_r}};{{base0B_rgb_g}};{{base0B_rgb_b}}" \
        "0;38;2;{{base09_rgb_r}};{{base09_rgb_g}};{{base09_rgb_b}}" \
        "0;38;2;{{base0A_rgb_r}};{{base0A_rgb_g}};{{base0A_rgb_b}}" \
        "0;38;2;{{base04_rgb_r}};{{base04_rgb_g}};{{base04_rgb_b}}" \
        "0;38;2;{{base04_rgb_r}};{{base04_rgb_g}};{{base04_rgb_b}}" \
        "1;38;2;{{base0D_rgb_r}};{{base0D_rgb_g}};{{base0D_rgb_b}}")
end

# man pages through bat, which is already themed — so this needs no colours of
# its own, only the plumbing to get there.
#
# Both halves are required, and both are version-specific facts about what the
# loadout actually ships:
#
#   col -bx   strips the backspace-overstrike bolding roff emits, which bat
#             would otherwise print literally. `col` is in util-linux.
#   MANROFFOPT=-c  tells grotty to emit that legacy overstrike instead of SGR
#             escapes. Required from groff 1.23 on; the MPR pins 1.24.1, so
#             without it the pipeline hands bat raw escape sequences.
#
# Guarded on all three binaries: man-db, bat and col each come from a different
# package, and a loadout with one of them dropped should lose the styling, not
# the ability to read a man page.
if command -q man; and command -q bat; and command -q col
    set -gx MANPAGER "sh -c 'col -bx | bat -l man -p'"
    set -gx MANROFFOPT -c
end

# difftastic picks brighter or darker colours from this; it has no way to ask
# the terminal. Decided by a dark/light section pair, as the duf alias is.
if command -q difft
    set -gx DFT_BACKGROUND {% if dark %}dark{% endif %}{% if light %}light{% endif %}
end

# $EDITOR is set in cozy.toml's [vars]; $VISUAL is the same answer for the
# programs that ask the other question. The two are not synonyms: $EDITOR is
# the fallback for when a full-screen editor can't be hosted — historically a
# line printer, today a pipe or a dumb terminal — and $VISUAL is the one to use
# when it can. Tools that distinguish them check $VISUAL first, so setting only
# $EDITOR quietly asks for the degraded answer everywhere that cares.
#
# Not in [vars], for the reason given there: every name added to it is another
# chance for a project's minimal.toml to disagree and fail the activation
# outright, so anything that can live in the shell config does.
#
# $GIT_EDITOR is deliberately *not* set, though it would be the obvious third
# line. git resolves $GIT_EDITOR before core.editor, so setting it would put
# the loadout ahead of an editor you chose yourself in your own gitconfig.
# Leaving it unset lets git fall through core.editor to $VISUAL, which reaches
# the same place here without overruling anyone. It is the same restraint the
# git includes are written with.
if command -q hx
    set -gx VISUAL hx
end

# --- Misc ---
# $fish_greeting is the banner, set up in the colours section above. Clear it
# with `set fish_greeting` here to go back to a silent shell.

# Forces the command line to be redrawn after every command, so a prompt that
# reports state the last command changed — starship's git status, its exit-code
# indicator — is repainted rather than left showing what was true before it ran.
#
# Inherited from the config this loadout was built from; the specific artefact
# it was added for isn't recorded, and fish redraws on its own in the common
# case. If you never see it do anything, it is safe to delete.
function __force_repaint --on-event fish_postexec
    commandline -f repaint
end
